---
- name: Add postgres 9.6 repository  
  become: true
  yum:
    name: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm
    state: present

- name: Install postgres 9.6
  become: true
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages: 
    - postgresql96 
    - postgresql96-server 
    - postgresql96-contrib 
    - postgresql96-libs

- name: Initialize pg database
  become: true
  ignore_errors: true
  shell: /usr/pgsql-9.6/bin/postgresql96-setup initdb

- name: Enable postgres service
  become: true
  systemd:
    name: postgresql-9.6.service
    enabled: yes
    state: started
