---
- name: Add postgres repository
  yum_repository:
    name: postgres
    base_url: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm

- name: Install postgres 9.3
  become: true
  yum:
    name: postgresql93 postgresql93-server postgresql93-contrib postgresql93-libs
    state: latest
